name: Trivy

permissions:
  contents: read
  actions: read
  security-events: write

on:
  pull_request:
  workflow_dispatch:
  push:

env:
  SARIF_FILE: 'trivy-results.sarif'

jobs:
  build:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Trivy vulnerability scanner on the cloned repository files
        uses: aquasecurity/trivy-action@0.33.1
        with:
          version: 'v0.68.1'
          scan-type: 'fs'
          scanners: 'vuln,misconfig,secret,license'
          ignore-unfixed: true
          format: 'sarif'
          output: ${{ env.SARIF_FILE }}
          severity: 'CRITICAL'
          trivyignores: '.trivyignore'

      - name: Check Trivy scan results existence
        run: |
          if [ ! -f "${{ env.SARIF_FILE }}" ]; then
            echo "Error: ${{ env.SARIF_FILE }} does not exist."
            exit 1
          fi
          ls -lash ${{ env.SARIF_FILE }}
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ env.SARIF_FILE }}

