name: Validate JSON, XML, and MD
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  json-yaml-md-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v4.0.0

      - name: markdown-validate
        id: markdown-validate
        uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: '**/*.md'
